import type { Metadata } from "next";
import "./globals.css";
import Provider from "@/components/templates/Provider";


export const metadata: Metadata = {
  title: "shahr ict task",
  description: "Generated by next15",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body className='antialiased' >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}


